---

- name: Add Nginx Repository
  apt_repository: repo=ppa:{{ nginx_ppa }} state=present
  register: ppa_added

- name: Install Nginx
  when: ppa_added | success
  apt: pkg=nginx state=installed update_cache=true
  register: nginx_installed
  notify: start nginx

- name: Remove Apache legacy folders
  when: nginx_installed|success
  file: path={{ item }} state=absent
  with_items:
    - "/etc/nginx/sites-enabled"
    - "/etc/nginx/sites-available"

- name: Setup htdocs folder
  when: nginx_installed | success
  file: >
    state=directory recurse=yes mode=0775
    path={{ doc_root }}
    group={{ www_group }}
    owner={{ www_user }}
  register: htdocs_created

- name: Place configuration files
  template: >
    src="{{ item.src }}"
    dest="{{ item.dest }}"
    owner=root group=root mode=0600
  with_items:
    - { src: 'nginx.conf.j2',        dest: '/etc/nginx/nginx.conf' }
    - { src: 'nginx_status.conf.j2', dest: '/etc/nginx/conf.d/nginx_status.conf' }
  register: placed_default_site

# Optional, set nginx_install_default=no to skip
- name: Place configuration files
  when: nginx_install_default
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root group=root mode=0600
  with_items:
    - { src: 'default.conf.j2', dest: '/etc/nginx/conf.d/default.conf' }
  notify: restart nginx

- name: Install HTML5 Biolerplate for Nginx
  when: h5bp_install == true
  include: install-h5bp.yml
